language: node_js
os:
  - linux
cache:
  yarn: true
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '8'
script:
  - npm run test
after_success:
  - npx ci-scripts github-post
  - npx ci-scripts slack
  - npm run semantic-release
